version: '2'
services:
  db:
    image: mongo
    volumes:
      - mongodb_data:/data/db
  web:
    build: .
    command: make serve
    environment:
      - MONGO_URI=mongodb://db
      - HOST_IP=0.0.0.0
    volumes:
      - .:/opt/webapp
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  mongodb_data:
